baseURL = 'https://github.com/frankheat/offsecnotes/'
languageCode = 'en-us'
title = 'offsecnotes'
theme = "mytheme"
enableGitInfo = true

[params]
  GITHUB_PROJECT = "https://github.com/frankheat/offsecnotes"
  AUTHOR = "frankheat"
  GITHUB_PROFILE = "https://github.com/frankheat"
  LINKEDIN_PROFILE = "https://www.linkedin.com/in/francesco-volpe98/"