baseURL = 'https://offsecnotes.frankheat.io/'
languageCode = 'en-us'
title = 'offsecnotes'
theme = "mytheme"
enableGitInfo = true
enableRobotsTXT = true

[params]
  AUTHOR = "frankheat"
  GITHUB_PROJECT = "https://github.com/frankheat/offsecnotes"
  GITHUB_PROFILE = "https://github.com/frankheat"
  LINKEDIN_PROFILE = "https://www.linkedin.com/in/francesco-volpe98/"